FROM python:3

#==============
# Expose Ports
#==============
EXPOSE 8089
EXPOSE 5557
EXPOSE 5558
EXPOSE 3000

#======================
# Install dependencies
#======================
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

#=====================
# Start docker-locust
#=====================
COPY tests /tests/

CMD locust -f tests/locustfile.py --slave --master-host=locust-master